### ISSUE TITLE
Function replacer not working

### ISSUE THREAD

**Issue by minwe** [041616/babel-plugin-replace-imports#1]
```javascript
_.isEmpty(function(){ return 'HELLO'});
// => true
```

`_.isEmpty(Function)` return  `true`,  then the plugin throw an error.

https://github.com/041616/babel-plugin-replace-imports/blob/626ebd3842b691bb64b2df222c27559de3b8f763/src/index.js#L48

**Comment by 041616** [comment]
Thanks for your bug report.
